### ISSUE TITLE
Setting persistance?

### ISSUE THREAD

**Issue by Ph0rkoz** [devksingh4/thinkpad-tools#12]
I set my track-point how I like with this tool and its great. Unfortunately it doesn't persist past reboots. I haven't checked suspend. I'm sure it can be scripted but it would be nice if the tool did this for me, otherwise its not as much of a time saver as one would hope.

I also couldn't figure out the battery syntax, having both an internal and external. I'd set things, get no errors but the status never reflected what I wrote. Not a big show stopper as I have TLP managing this but just thought you'd like to know.

**Comment by devksingh4** [comment]
The persistence could be done with a service in systemd. I'm not sure how to do this but I will do some research. If anyone would like to help that would be great. 

I will see whats going on with the battery feature. It also seems to not be applying for me as well.

**Comment by devksingh4** [comment]
Persistence support added with systemd service and script.
