### ISSUE TITLE
) missing in battery.py L104

### ISSUE THREAD

**Issue by Garionion** [devksingh4/thinkpad-tools#13]
Hey,
there is a ) missing in [battery.py L104](https://github.com/devksingh4/thinkpad-tools/blob/master/assets/battery.py#L104)

it has to be `if type(kwargs[prop]) == type(default_value):`
and not `if type(kwargs[prop] == type(default_value):`

**Comment by devksingh4** [comment]
Fixed, thanks for reporting!
