### ISSUE TITLE
consider configparser or other similar "real" config file 

### ISSUE THREAD

**Issue by mattdm** [devksingh4/thinkpad-tools#15]
Right now, the persistent-settings functionality is implemented via a systemd service which calls a shell script which calls the main command (possibly multiple times) on boot.

Rather than doing this, why not have the service run a python command which reads a config file and sets all options as appropriate?

Advantages:

* slightly faster
* no need for both bash and python
* less error prone
* possibility for better handling if there are typos, etc.
* can't be abused to run other random commands
* a fixed config-file syntax easier to read and write from other tools like Cockpit or Ansible

https://docs.python.org/3/library/configparser.html (but there are lots of options)

**Comment by devksingh4** [comment]
The bash script is a temporary solution, I've been looking into implementing something like this which would just call the correct commands in python.
