### ISSUE TITLE
TrackPoint  status  always shows " Unknown"  

### ISSUE THREAD

**Issue by Cavefishy** [devksingh4/thinkpad-tools#19]
**Describe the bug**
TrackPoint  status  always shows " Unknown" , after set-Sensitivity or Speed value.
I guess there is something wrong with my  BASE_PATH, but I don't know how to find the correct path.
**To Reproduce**

> $ sudo thinkpad-tools   trackpoint status 
> Current status:
>   Sensitivity:             Unknown
>   Speed:                   Unknown
> $ sudo thinkpad-tools trackpoint set-Speed 254
> Current status:
>   Sensitivity:             Unknown
>   Speed:                   254
> $ sudo thinkpad-tools   trackpoint status 
> Current status:
>   Sensitivity:             Unknown
>   Speed:                   Unknown
> 

**Expected behavior**
Maybe my BASE_PATH doesn't exist:
> $ sudo find / -name "serio?"               
> /sys/devices/platform/i8042/serio0
> /sys/devices/platform/i8042/serio1
> /sys/bus/serio/devices/serio0
> /sys/bus/serio/devices/serio1
> /sys/bus/serio/drivers/atkbd/serio0
> /sys/bus/serio/drivers/psmouse/serio1

**Desktop (please complete the following information):**
 - OS: [Ubuntu 20.04]
 - Version: [20.04 LTS]
 - Python Version [e.g. 3.8.2 64-bit]
 - Thinkpad Model [e.g. T480s]

**Additional context**

> $ xinput --list                                             
> ⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
> ⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
> ⎜   ↳ Elan Touchpad                           	id=12	[slave  pointer  (2)]
> ⎜   ↳ Elan TrackPoint                         	id=13	[slave  pointer  (2)]
> ⎜   ↳ TEX-BLE-KB-1 Mouse                      	id=16	[slave  pointer  (2)]
> .....
>input --list-props 13                                      17:07:50

> Device 'Elan TrackPoint':
> 	Device Enabled (171):	1
> 	Coordinate Transformation Matrix (173):	1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000
> 	libinput Natural Scrolling Enabled (314):	0
> 	libinput Natural Scrolling Enabled Default (315):	0
> 	libinput Scroll Methods Available (318):	0, 0, 1
> 	libinput Scroll Method Enabled (319):	0, 0, 1
> 	libinput Scroll Method Enabled Default (320):	0, 0, 1
> 	libinput Button Scrolling Button (332):	2
> 	libinput Button Scrolling Button Default (333):	2
> 	libinput Middle Emulation Enabled (324):	0
> 	libinput Middle Emulation Enabled Default (325):	0
> 	libinput Accel Speed (326):	0.500000
> 	libinput Accel Speed Default (327):	0.000000
> 	libinput Accel Profiles Available (334):	1, 1
> 	libinput Accel Profile Enabled (335):	1, 0
> 	libinput Accel Profile Enabled Default (336):	1, 0
> 	libinput Left Handed Enabled (328):	0
> 	libinput Left Handed Enabled Default (329):	0
> 	libinput Send Events Modes Available (291):	1, 0
> 	libinput Send Events Mode Enabled (292):	0, 0
> 	libinput Send Events Mode Enabled Default (293):	0, 0
> 	Device Node (294):	"/dev/input/event6"
> 	Device Product ID (295):	1267, 32
> 	libinput Drag Lock Buttons (330):	<no items>
> 	libinput Horizontal Scroll Enabled (331):	1

**Comment by palytoxin** [comment]
same problem,

Desktop (please complete the following information):

OS: [LinuxMint]
Version: [ 19.3]
Python Version [3.8.0]
Thinkpad Model [X1C7]

**Comment by devksingh4** [comment]
I am in a T480 on Ubuntu 20.04 and have not encountered this issue. I think you are correct in that the issue is with the base path. I will add your base path and have you try it again. 

@palytoxin can you provide the same `find` output that @Cavefishy did?

**Comment by devksingh4** [comment]
@Cavefishy can I get the output on the `ls` for all of these folders on your machine: 

```/sys/devices/platform/i8042/serio0
/sys/devices/platform/i8042/serio1
/sys/bus/serio/devices/serio0
/sys/bus/serio/devices/serio1
/sys/bus/serio/drivers/atkbd/serio0
/sys/bus/serio/drivers/psmouse/serio1
```
Along with the output of: `sudo find /sys -name "sensitivity"`

**Comment by palytoxin** [comment]
sudo find /sys -name "sensitivity"
`/sys/devices/platform/i8042/serio1/sensitivity`

```
home> ll /sys/bus/serio/devices/serio0
lrwxrwxrwx 1 root root 0 Jun 10  2020 /sys/bus/serio/devices/serio0 -> ../../../devices/platform/i8042/serio0/

home> ll /sys/bus/serio/devices/serio1 
lrwxrwxrwx 1 root root 0 Jun 10  2020 /sys/bus/serio/devices/serio1 -> ../../../devices/platform/i8042/serio1/

home> ll /sys/bus/serio/drivers/atkbd/serio0
lrwxrwxrwx 1 root root 0 Jun 10 10:07 /sys/bus/serio/drivers/atkbd/serio0 -> ../../../../devices/platform/i8042/serio0/

home> ll /sys/bus/serio/drivers/psmouse/serio1
lrwxrwxrwx 1 root root 0 Jun 10 10:07 /sys/bus/serio/drivers/psmouse/serio1 -> ../../../../devices/platform/i8042/serio1/

home> ls /sys/devices/platform/i8042/serio1
bind_mode    driver@  firmware_id  input/    power/           protocol  resetafter  resync_time  subsystem@
description  drvctl   id/          modalias  press_to_select  rate      resolution  sensitivity  uevent

home> cd /sys/bus/serio/devices/serio0;ls    
bind_mode    drvctl     firmware_id    input/    scroll   softrepeat
description  err_count  force_release  modalias  set      subsystem@
driver@      extra      id/            power/    softraw  uevent

/:serio0(5)> cd /sys/bus/serio/devices/serio1;ls  
bind_mode    drvctl       input/    press_to_select  resetafter   sensitivity
description  firmware_id  modalias  protocol         resolution   subsystem@
driver@      id/          power/    rate             resync_time  uevent

/:serio1(5)> cd /sys/bus/serio/drivers/atkbd/serio0;ls
bind_mode    drvctl     firmware_id    input/    scroll   softrepeat
description  err_count  force_release  modalias  set      subsystem@
driver@      extra      id/            power/    softraw  uevent

/:serio0(5)> cd /sys/bus/serio/drivers/psmouse/serio1;ls
bind_mode    drvctl       input/    press_to_select  resetafter   sensitivity
description  firmware_id  modalias  protocol         resolution   subsystem@
driver@      id/          power/    rate             resync_time  uevent


```

**Comment by devksingh4** [comment]
None of these directories seem to contain the 'speed' register, which is needed for functionality. What ThinkPad is this? It's possible something with the drivers has changed which makes it incompatible with this tool. However, I don't see this issue on Ubuntu 20.04 so I'm not sure what driver would have changed.

**Comment by devksingh4** [comment]
No response received, so closing for now as stale.
