### ISSUE TITLE
thinkpad-tools.py doesn't work if invoked by PATH.

### ISSUE THREAD

**Issue by moondeck** [devksingh4/thinkpad-tools#2]
Hello,
It seems like thinkpad-tools.py doens't work when invoked in a shell after installing. I can use it inside the cloned repo folder with `./thinkpad-tools.py` but not by `sudo thinkpad-tools.py`. The latter throws up:
`Traceback (most recent call last):
  File "/usr/bin/thinkpad-tools.py", line 8, in <module>
    import Handlers
ModuleNotFoundError: No module named 'Handlers'
`

Which i think maybe caused by setup.sh putting Handlers.py in /usr/lib, which is not a directory that python searches for modules. A fix i would propose is either finding a way to determine the directory python uses to search for modules, reliably (no guesswork), or creating a folder in `~/.local/opt` that will hold a install of the program. I'll  be happy to work on figuring this out.

**Comment by devksingh4** [comment]
Possibly creating a symbolic link between the two folders?

**Comment by devksingh4** [comment]
I'd rather be making a proper .deb and .rpm package to be honest, so this setup.sh is a temporary measure until I figure that out (and if you'd like to help figure that out be my guest!)

**Comment by devksingh4** [comment]
Tested working Ubuntu 18.04 and Arch Linux
