### ISSUE TITLE
Speed and sensitivity settings don't do anything, consider implementing "disable trackpoint"

### ISSUE THREAD

**Issue by ripefig** [devksingh4/thinkpad-tools#9]
I tried values of 0 to 100 for both and there is no effect on a t440 (the one with integrate trackpoint buttons combo) on Ubuntu19.04.

Then again the trackpoint buttons don't work at all with the conventional touchpad settings enabled (top to click and gestures), and they barely work with those settings disabled. Even more seriously, the touchpad palm rejection makes the trackpoint itself completely unusable - if you rest your hands normally while using the trackpoint, you will touch the touchpad with your palm and this will cause the trackpoint to stop moving entirely.

So at least on my system, the trackpoint doesn't work at all. I suspect that longstanding palm rejection bug this is a fundamental libinput issue affecting all linux distros and all thinkpads. I remember the buttons sort of barely working on Ubuntu 18.04 but the basic palm rejection bug has been there from the beginnings of libinput. There is no way this will ever get fixed.

*Do we actually know if any modern thinkpad trackpoints work on Linux at all?* If the answer is no, then the only relevant trackpoint setting is "disable trackpoint." It's possible that trackpoints work on the thinkpads that are 10 years old (where palm interference wasn't an issue) but the new ones are probably all broken.

**Comment by devksingh4** [comment]
Yes trackpoint works just fine on Linux for all modern thinkpads, with palm
rejection. The value range is also 0-255, with both values 0 meaning the
trackpoint is disabled.

I suspect the trackpoint edit not working has to do with newer distros
using rmi to interface with trackpoint, where as older distros use
serio1/serio2. I will have to do some research to see how to get both to
work, but it should just be a matter of checking if one file exists and if
not using the other file.

**Comment by ripefig** [comment]
Are you using Ubuntu? 

This bug is still open, for T450, which has different input hardware, but it's slightly different than mine: it just says the trackpoint is slow and the speed can't be changed without recompiling libinput or something:
https://bugs.launchpad.net/ubuntu/+source/libinput/+bug/1733083

I've tried 440, 450 and and 430 over several years with Ubuntu and libinput. All of them had serious issues with the trackpoint and (previously) touchpad that made it impossible to use the computer without a conventional external mouse.

**Comment by devksingh4** [comment]
I am using Debian but have previously used Ubuntu. It worked fine on my
T480. I don't think the file edited relies on libinput; it edits the buffer
which the trackpoint exposes to the system

**Comment by devksingh4** [comment]
I just published a patch which may fix this problem, please try now

**Comment by ripefig** [comment]
No, it still doesn't affect the speed or sensitivity.

**Comment by devksingh4** [comment]
Feature to disable trackpoint added.
